In [3]:
import cv2
import pickle
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.svm import SVC

%matplotlib inline

In [22]:
with open('.\dataset\ck.pikle','rb') as f:
    ck_data, ck_label = pickle.load(f)
    
ck_data_train, ck_data_test, ck_label_train, ck_label_test = train_test_split(ck_data, ck_label, test_size=0.25, random_state=42)

In [55]:
lda = LinearDiscriminantAnalysis(solver='svd').fit(ck_data_train, ck_label_train)
pca = PCA(n_components=6, svd_solver='randomized', whiten=True).fit(lda.transform(ck_data_train))

ck_data_train_ipca = pca.transform(lda.transform(ck_data_train))
ck_data_test_ipca = pca.transform(lda.transform(ck_data_test))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")


In [56]:
target_classes = ["Neutral", "Angry", "Disgust", "Fear", "Happy", "Sad", "Surprise"]

clf = SVC(kernel='rbf', class_weight='balanced', gamma=0.0001, C=1000.0)

clf = clf.fit(ck_data_train_ipca, ck_label_train)
ck_label_predict = clf.predict(ck_data_test_ipca)

print(classification_report(ck_label_test, ck_label_predict, target_names=target_classes))
print(confusion_matrix(ck_label_test, ck_label_predict, labels=range(7)))

              precision    recall  f1-score   support

     Neutral       0.57      0.62      0.59        13
       Angry       0.53      0.57      0.55        14
     Disgust       1.00      0.82      0.90        17
        Fear       0.71      0.71      0.71         7
       Happy       1.00      0.91      0.95        11
         Sad       0.30      0.50      0.37         6
    Surprise       1.00      0.86      0.92        14

   micro avg       0.73      0.73      0.73        82
   macro avg       0.73      0.71      0.72        82
weighted avg       0.78      0.73      0.75        82

[[ 8  2  0  0  0  3  0]
 [ 4  8  0  0  0  2  0]
 [ 1  1 14  1  0  0  0]
 [ 0  1  0  5  0  1  0]
 [ 1  0  0  0 10  0  0]
 [ 0  3  0  0  0  3  0]
 [ 0  0  0  1  0  1 12]]
