In [16]:
import cv2
import pickle
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.decomposition import PCA
from sklearn.svm import SVC

%matplotlib inline

In [43]:
with open('.\dataset\ck.pikle','rb') as f:
    ck_data, ck_label = pickle.load(f)
    
ck_data_train, ck_data_test, ck_label_train, ck_label_test = train_test_split(ck_data, ck_label, test_size=0.25, random_state=42)

In [62]:
pca = PCA(n_components=244, svd_solver='randomized', whiten=True).fit(ck_data_train)
ck_data_train_pca = pca.transform(ck_data_train)
ck_data_test_pca = pca.transform(ck_data_test)

In [63]:
target_classes = ["Neutral", "Angry", "Disgust", "Fear", "Happy", "Sad", "Surprise"]

clf = SVC(kernel='rbf', class_weight='balanced', gamma=0.0001, C=1000.0)

clf = clf.fit(ck_data_train_pca, ck_label_train)
ck_label_predict = clf.predict(ck_data_test_pca)

print(classification_report(ck_label_test, ck_label_predict, target_names=target_classes))
print(confusion_matrix(ck_label_test, ck_label_predict, labels=range(7)))

              precision    recall  f1-score   support

     Neutral       0.62      0.38      0.48        13
       Angry       0.56      0.71      0.63        14
     Disgust       0.71      0.88      0.79        17
        Fear       1.00      0.43      0.60         7
       Happy       1.00      1.00      1.00        11
         Sad       0.14      0.17      0.15         6
    Surprise       1.00      1.00      1.00        14

   micro avg       0.72      0.72      0.72        82
   macro avg       0.72      0.65      0.66        82
weighted avg       0.74      0.72      0.71        82

[[ 5  3  3  0  0  2  0]
 [ 1 10  2  0  0  1  0]
 [ 1  0 15  0  0  1  0]
 [ 1  1  0  3  0  2  0]
 [ 0  0  0  0 11  0  0]
 [ 0  4  1  0  0  1  0]
 [ 0  0  0  0  0  0 14]]
