In [13]:
import cv2
import pickle
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.decomposition import PCA
from sklearn.svm import SVC

%matplotlib inline

In [14]:
with open('./dataset/ck.pikle','rb') as f:
    ck_data, ck_label = pickle.load(f)
    
ck_data_train, ck_data_test, ck_label_train, ck_label_test = train_test_split(ck_data, ck_label, test_size=0.25, random_state=42)

In [15]:
pca = PCA(n_components=244, svd_solver='randomized', whiten=True).fit(ck_data_train)
ck_data_train_pca = pca.transform(ck_data_train)
ck_data_test_pca = pca.transform(ck_data_test)

In [16]:
target_classes = ["Neutral", "Angry", "Disgust", "Fear", "Happy", "Sad", "Surprise"]

clf = SVC(kernel='rbf', class_weight='balanced', gamma=0.0001, C=1000.0)

clf = clf.fit(ck_data_train_pca, ck_label_train)
ck_label_predict = clf.predict(ck_data_test_pca)

print(classification_report(ck_label_test, ck_label_predict, target_names=target_classes))
print(confusion_matrix(ck_label_test, ck_label_predict, labels=range(7)))
print(accuracy_score(ck_label_test, ck_label_predict))

              precision    recall  f1-score   support

     Neutral       0.64      0.58      0.61        12
       Angry       0.73      0.73      0.73        11
     Disgust       0.83      0.91      0.87        11
        Fear       0.80      0.67      0.73         6
       Happy       0.94      1.00      0.97        15
         Sad       0.50      0.83      0.62         6
    Surprise       1.00      0.81      0.89        21

   micro avg       0.80      0.80      0.80        82
   macro avg       0.78      0.79      0.77        82
weighted avg       0.83      0.80      0.81        82

[[ 7  1  2  0  0  2  0]
 [ 1  8  0  1  0  1  0]
 [ 0  1 10  0  0  0  0]
 [ 0  0  0  4  1  1  0]
 [ 0  0  0  0 15  0  0]
 [ 0  1  0  0  0  5  0]
 [ 3  0  0  0  0  1 17]]
0.8048780487804879
